### ISSUE TITLE
Add Rock Smash to the PRNG seed calculator

### ISSUE THREAD

**Issue by glu8716** [E-Sh4rk/CodeGenerator#2]
I read from the guide [here](https://e-sh4rk.github.io/EmeraldACE_web/doc/PRNG_stall_guide.pdf) that the Rock Smash case for the "Freeze PRNG" code isn't supported yet in the seed calculator. Would it be possible to add it?

Thanks in advance!

**Comment by E-Sh4rk** [comment]
I did not make the fishing rod seed calculator script myself, but I can try to do the smash rock one, I guess it should not be too complicated with the decomp :)

**Comment by glu8716** [comment]
Thank you! That would be much appreciated :)

**Comment by glu8716** [comment]
Hi! Any news on this? I also want to add a little bit of information without having to open a new issue if you want to add these to the script.
Both Mew, Lugia, Ho-Oh and Lati@s (Southern Island) are on cycle -3. Stationary Kecleon is -4 and fossils are -3 (got all of these by using the seeds I got from the "other" option).

**Comment by E-Sh4rk** [comment]
Hello! Thank you for your findings, I have added the data to the seed tool.

About rock smash, after some tests it seems to always be -3 cycles. So it does not need a more complex algorithm like for fishing. I have added the option in the seed tool. I'll close the issue, don't hesitate to open it again if it does not work.

**Comment by glu8716** [comment]
@E-Sh4rk Thanks for the prompt reply! I think I don't have the permissions to open the issue again. 
I've tried but unfortunately it doesn't seem to work for me. As soon as you exit from the Pokédex certificate there is a small window of time where the seed is frozen correctly, but then there are 2 more advancements, probably because of rocks being considered as NPCs. Here's a video with the lua script in action where you can see the current seed and the advancements. 

https://github.com/user-attachments/assets/54902a15-eb69-453a-8623-9f4a7b8aaafb

**Comment by E-Sh4rk** [comment]
You should follow the instructions for wild pokemons, in particular the thing about nicknaming a Pokemon ␣ ␣ D n ’ J k l ␣ ␣ and putting it after your exit code bootstrap, so that the diploma does not show.

**Comment by glu8716** [comment]
Oh, my bad, I haven't thought of it as Sweet Scent wasn't involved in this case. You're right, this works! Thanks a lot again  for all of your effort.

(and by the way, there is a typo in the script, as it is "stationary" and not "stationnary")
